# The MIT License (MIT)
#
# Copyright (c) 2017 Mateusz Pusz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

sudo: false
language: python
python:
  - "2.7"

install:
  - |
    # Install Bikeshed
    git clone https://github.com/tabatkins/bikeshed.git
    pip install --editable $PWD/bikeshed
    bikeshed update

script:
  - |
    # Run Bikeshed
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep .bs$ | xargs -n1 -t -r bikeshed spec

  - |
    # Prepare output to deploy
    travis_retry wget https://github.com/mpusz/wg21_papers/archive/gh-pages.zip
    unzip gh-pages.zip
    rm -rf wg21_papers-gh-pages/deployed\ at*
    shopt -s nullglob
    set -- src/*.html
    if [ "$#" -gt 0 ]; then
      mv "$@" wg21_papers-gh-pages/papers
    fi

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: wg21_papers-gh-pages
 on:
   branch: master
